# Generated by Django 6.0.3 on 2026-03-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва кольору')),
                ('hex_code', models.CharField(default='#000000', max_length=7, verbose_name='HEX колір')),
                ('image', models.ImageField(upload_to='shoes/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Колір взуття',
                'verbose_name_plural': 'Кольори взуття',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('size', models.CharField(max_length=5, verbose_name='Розмір')),
                ('city_name', models.CharField(max_length=200, verbose_name='Місто')),
                ('city_ref', models.CharField(blank=True, max_length=100, verbose_name='Ref міста НП')),
                ('warehouse_name', models.CharField(max_length=300, verbose_name='Відділення НП')),
                ('warehouse_ref', models.CharField(blank=True, max_length=100, verbose_name='Ref відділення НП')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('shoe_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shoecolor', verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
