# Generated by Django 6.0.1 on 2026-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ad_group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Група оголошень (?g=)'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='UTM Term'),
        ),
    ]
