# Generated by Django 6.0.1 on 2026-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_ad_group_order_utm_campaign_order_utm_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ref міста НП'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Відділення НП'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ref відділення НП'),
        ),
    ]
