# Generated by Django 6.0.1 on 2026-03-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_make_order_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name="Ім'я"),
        ),
    ]
